### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by mgefvert** [mj1856/Dapper-NodaTime#3]
Hi, I cloned your repository and found that support for .NET Standard 2.0 is included, which is what I need - however, this doesn't seem to be included in the nuget distribution? I've added it manually to my project for now.

Would be great if you could publish the new version... :)

**Comment by mattjohnsonpint** [comment]
Huh, not sure how I missed that.  Also looks like I had made a typo in the package id.  ;)

All fixed now.  Release as version 0.1.0.

Thanks.

**Comment by mgefvert** [comment]
Awesome - thank you!
